export { LOUP_GAROU_RULES } from './rules.js'
export { ROLES, getRoleById, distributeRoles } from './roles.js'
export { buildSystemPrompt } from './prompt.js'
export type { LoupGarouState } from './prompt.js'
export type { Role } from './roles.js'
